name: build-data-pull

on:
  push:
    branches:
    - "prod"
    paths:
    - "data_pull/*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set workdir
      run: cd data_pull
    - name: add config
      run: echo "${{ secrets.GEE_CREDENTIALS }}" | base64 -d >> credentials.json
    - name: Set container name
      run: echo "CONTAINER_NAME=ndvi-data-pull" >> $GITHUB_ENV
    - name: Get date and hash
      run: echo "TAG=$(date --iso-8601)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.PUSH_PACKAGE_USERNAME }}
        password: ${{ secrets.PUSH_PACKAGE_TOKEN }}
    - name: Build container
      run: docker build . --tag ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:${{ env.TAG }}
    - name: Tag the container as latest
      run: docker tag ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:${{ env.TAG }} ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:latest
    - name: Push the container
      run: docker push ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:${{ env.TAG }} && docker push ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:latest
          